feature(content): add post, read and delete content
BobAnkh/THUBurrow pull request #13
Opened 2021-11-07 12:38 UTC by Mofuko1316

## Description
Roughly complete the feature of posting, reading and deleting subject and reply content.
- [x] content post: receive corresponding data of subject post and save in database
- [x] content reply: receive corresponding data of reply of a specific post and save in database
- [x] content read: receive post id and page information of a specific subject post, return corresponding data of subject post with no more than 10 replies in one page
- [x] subject post delete: receive post id and delete subject post as well as its replies in database
- [x] reply delete: receive post id and reply id and delete reply of a specific subject post in database

## How Has This Been Tested
Send request with corresponding data using APIfox.
1. request for posting content (with corresponding data/ data with missing parts)
2. request for replying a specific post (with corresponding data/ data with missing parts)
3. request for reading a specific post with no more than 10 replies in one page
4. request for deleting a post (with post id that exists/ not exists)
5. request for deleting a reply of a specific post (with post id and reply id that exists/ not exists)

## Screenshots(optional)

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] Code follows the code style of this project.
- [x] Changes follow the **CONTRIBUTING** guidelines.
- [x] Update necessary documentation accordingly.
- [x] Lint and tests pass locally with the changes.
- [x] Check issues and pull requests first. You don't want to duplicate effort.

## Other information

2021-11-07 18:15 UTC, BobAnkh requested changes
Roughly review all the interface, not the code

Please polish the interfaces and **do a cargo clippy check** locally to improve code. Also can see what github actions provide you, or auto comments.

2021-11-07 18:15 UTC, BobAnkh commented on backend/src/routes/content.rs
> +#[get("/<post_id>/<page>")]
change uri to "`/post/<post_id>?<page>`", use a query string format

2021-11-07 18:15 UTC, BobAnkh commented on backend/src/routes/content.rs
> +#[post("/<post_id>/reply", data = "<reply_info>", format = "json")]
change uri to "/post/<post_id>/reply"

2021-11-07 18:15 UTC, BobAnkh commented on backend/src/routes/content.rs
> +#[delete("/<post_id>/delete")]
change uri to "/post/<post_id>"

2021-11-07 18:15 UTC, BobAnkh commented on backend/src/routes/content.rs
> +pub async fn content_delete_reply(
change uri to "/post/<post_id>/reply/<reply_id>", information can be carried in json data body

2021-11-12 03:11 UTC, Mofuko1316 commented on backend/src/req/content.rs
> +    pub post_len: i32,
remove anonymous, merge tag1~tag3

2021-11-12 11:41 UTC, BobAnkh commented on backend/src/routes/content.rs
> +                .await
You can use paginator:

https://www.sea-ql.org/SeaORM/docs/basic-crud/select#paginate-result

https://docs.rs/sea-orm/0.3.2/sea_orm/struct.Paginator.html

2021-12-03 02:47 UTC, BobAnkh commented
# TODO

## Valid burrow interface

## Cargo test consumer

2021-12-03 04:06 UTC, BobAnkh commented
# TODO

## Check consumer in relation write

2021-12-09 08:44 UTC, closed without merging