Feature/pulsar
BobAnkh/THUBurrow pull request #19
Opened 2021-11-16 06:01 UTC by h-guo18

## Description

加入搜索引擎和消息队列，实现搜索功能；

backend将洞、帖、回复的增删改信息通过pulsar传递给typesense，由后者记录在其数据库中并向backend提供搜索接口；

消息队列：pulsar，搜索引擎：typesense；

## How Has This Been Tested

## Screenshots(optional)

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] Code follows the code style of this project.
- [x] Changes follow the **CONTRIBUTING** guidelines.
- [ ] Update necessary documentation accordingly.
- [ ] Lint and tests pass locally with the changes.
- [ ] Check issues and pull requests first. You don't want to duplicate effort.
- [ ] 功能：在typesense中记录洞、帖、回复的增删改
- [ ] 功能：typesense-backend接口，返回搜索结果给backend

## Other information

2021-11-19 13:24 UTC, h-guo18 commented on backend/src/bin/consumer/main.rs
> +        {"name": "id", "type": "int64"},
改变量名

2021-11-19 13:24 UTC, h-guo18 commented on backend/src/bin/consumer/main.rs
> +        {"name": "post_type", "type": "int32"},
int16，如果支持

2021-11-19 13:27 UTC, h-guo18 commented on backend/src/bin/consumer/main.rs
> +        // TODO: match the status code of Response here, to see whether it is successfully created or is already created, or failed
匹配错误

2021-11-19 13:28 UTC, h-guo18 commented on backend/src/bin/consumer/main.rs
> +impl Typesense for reqwest::Client {
如果需要加新接口

2021-11-19 13:31 UTC, h-guo18 commented on backend/src/bin/consumer/main.rs
> +                    .body(serde_json::to_string(&operation).unwrap())
可以传结构体

2021-11-19 13:31 UTC, h-guo18 commented on backend/src/bin/consumer/main.rs
> +                    "created_time":data.operation_time,
删掉

2021-11-19 13:33 UTC, h-guo18 commented on backend/src/bin/consumer/main.rs
> +        {"name": "post_type", "type": "int32"},
tag+section

2021-11-19 13:33 UTC, h-guo18 commented on backend/src/bin/consumer/main.rs
> +        {"name": "id", "type": "int64"},
真实id：uid，洞：burrow_id

2021-11-19 13:33 UTC, h-guo18 commented on backend/src/bin/consumer/main.rs
> +        {"name": "post_type", "type": "int32"},
tags：分区+剩余tag，sec是分区

2021-11-25 11:20 UTC, BobAnkh requested changes

2021-11-25 11:20 UTC, BobAnkh commented on backend/src/bin/consumer/main.rs
> +                409 => panic!("Conflict - When a resource already exists."),
This should not panic. Imagine a case: you run this script twice, so you create the resource twice. This should not stop the program running: You have it created correctly!

2021-11-25 11:20 UTC, BobAnkh commented on backend/src/bin/consumer/main.rs
> +                .await.unwrap().text().await.unwrap()).unwrap();
do not use so many times of unwrap here. It one of them panic, you will never know who causes it.

2021-11-25 11:20 UTC, BobAnkh commented on backend/src/bin/consumer/main.rs
> +                            < burrow.update_time.timestamp()
Can it be directly compared? Not tranforming to timestamp?

2021-11-25 11:20 UTC, BobAnkh commented on backend/src/bin/consumer/main.rs
> +                .build_get(&format!("/collections/burrows/documents/search?q={}&query_by=burrow_id&filter_by=&sort_by=",burrow.burrow_id))
here you have the burrow id, I think you don't need to perform a search. Simply get the document.

2021-11-25 11:20 UTC, BobAnkh commented on backend/src/routes/search.rs
> +    let uri = format!("/collections/replies/documents/search?q={}&query_by=content&filter_by=tag:= {}&group_by=post_id&sort_by=update_time", keyword,tag);
Can this interface work?I see here a space inside the uri

2021-11-25 11:20 UTC, BobAnkh commented on backend/src/routes/search.rs
> +        .to_string(),
return json, not string

2021-11-25 11:20 UTC, BobAnkh commented on backend/src/routes/search.rs
> +    }
when given only postid, just use sea-orm of postgres, no need to touch typesense.

2021-11-25 11:20 UTC, BobAnkh commented on backend/src/routes/search.rs
> +    }
when given only burrowid, use sea-orm to search postgres, no need to touch typesense

2021-11-27 10:39 UTC, BobAnkh requested changes
Change your search request to enum. I have mentioned this.

Merge all the search interfaces into one. Use enum to decide the search type.

2021-11-27 10:39 UTC, BobAnkh commented on backend/src/bin/consumer/main.rs
> +                    .build_get(&format!("/collections/posts/documents/search?q={}&query_by=post_id&filter_by=&sort_by=",post.post_id))
retrieve it when you have the post id

2021-11-27 10:39 UTC, BobAnkh commented on backend/src/bin/consumer/main.rs
> +                            < post.update_time.timestamp()
same problem as above mentioned

2021-11-27 10:39 UTC, BobAnkh commented on backend/src/bin/consumer/main.rs
> +                    .build_get(&format!("/collections/replies/documents/search?q={}&query_by=reply_id&filter_by=&sort_by=",reply.reply_id))
same problem

2021-11-27 10:39 UTC, BobAnkh commented on backend/src/req/pulsar.rs
> +}
Use enum to filter different kind of search

2021-11-27 10:39 UTC, BobAnkh commented on backend/src/routes/search.rs
> +                (None, None, Some(_tag)) => {
Do not use redirect.

2021-11-27 10:39 UTC, BobAnkh commented on backend/src/routes/search.rs
> +            retrieve_post
No need to have so much function and interfaces. merge them into one

2021-11-28 04:00 UTC, h-guo18 commented
![image](https://user-images.githubusercontent.com/67671475/143728878-1467856a-f7ca-4bfd-8096-e52d1c661c9c.png)
![image](https://user-images.githubusercontent.com/67671475/143728910-1976054a-3450-4b95-9f69-394cc2828e7b.png)
![image](https://user-images.githubusercontent.com/67671475/143728931-599ca619-5dc1-4c2c-ab57-54734cfd0719.png)
![image](https://user-images.githubusercontent.com/67671475/143728944-c5cad0a9-d3b0-44cb-be85-2d3b18a9d041.png)
![image](https://user-images.githubusercontent.com/67671475/143728948-f5c93c39-a513-47c7-85dc-3d62f77d64eb.png)
![image](https://user-images.githubusercontent.com/67671475/143728953-56c7243f-9de8-47b5-abb9-f173c21d4bd8.png)
![image](https://user-images.githubusercontent.com/67671475/143728977-36692680-0053-4d22-8228-c67def51a0b6.png)
![image](https://user-images.githubusercontent.com/67671475/143728983-11c076ef-79f1-4148-938b-ca9dd3b5c220.png)
![image](https://user-images.githubusercontent.com/67671475/143728993-42b2cce9-c2d4-482b-943b-910b8be46adf.png)
![image](https://user-images.githubusercontent.com/67671475/143728998-5203492a-db8a-4e98-8ed4-34519c60139e.png)

2021-12-09 08:44 UTC, closed without merging